name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' }

permissions: read-all

jobs:
  release:
    permissions: { contents: write }
    uses: nodenv/.github/.github/workflows/release.yml@v4
    secrets: inherit

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          scope: nodenv
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
